<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-11-10T22:57:22 IST" name="Suite12" finished-at="2023-11-10T22:57:26 IST" duration-ms="3968">
    <groups>
    </groups>
    <test started-at="2023-11-10T22:57:22 IST" name="Error Validation Test" finished-at="2023-11-10T22:57:26 IST" duration-ms="3968">
      <class name="Satyagrpid.saiaid.ErrorValidations">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Satyagrpid.saiaid.ErrorValidations@5745ca0e]" started-at="2023-11-10T22:57:22 IST" name="launchApplication" finished-at="2023-11-10T22:57:25 IST" duration-ms="2903" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="errorvalidationTest()[pri:0, instance:Satyagrpid.saiaid.ErrorValidations@5745ca0e]" started-at="2023-11-10T22:57:25 IST" name="errorvalidationTest" finished-at="2023-11-10T22:57:25 IST" duration-ms="567" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email or password1.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email or password1.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at Satyagrpid.saiaid.ErrorValidations.errorvalidationTest(ErrorValidations.java:21)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1589)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- errorvalidationTest -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:Satyagrpid.saiaid.ErrorValidations@5745ca0e]" started-at="2023-11-10T22:57:25 IST" name="teardown" finished-at="2023-11-10T22:57:26 IST" duration-ms="84" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- Satyagrpid.saiaid.ErrorValidations -->
    </test> <!-- Error Validation Test -->
  </suite> <!-- Suite12 -->
</testng-results>
